<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkout Options</name>
   <tag></tag>
   <elementGuidId>6042bac3-7ff3-4e92-8a70-959f36c1bf89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.panel-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(), &quot;Checkout Options&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>78a2ecaf-5d6f-4c36-8915-4de40e6a4aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-title</value>
      <webElementGuid>75dfd596-00c3-488a-8545-8650d0c0dfcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Step 1: Checkout Options</value>
      <webElementGuid>2a1125e6-4b63-443a-8b82-5a107a00f1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]</value>
      <webElementGuid>43da4b08-4297-4192-bbb1-7cfe2286d4fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/h4</value>
      <webElementGuid>aa9c0b96-f070-491d-b4e6-d91cfff509c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>d67f77c1-6ab2-4c9b-aa1f-b193cbc4d9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Step 1: Checkout Options' or . = 'Step 1: Checkout Options')]</value>
      <webElementGuid>46656314-4dcb-497a-aa41-181c751229ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
