<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1-Checkout</name>
   <tag></tag>
   <elementGuidId>9a122137-fe75-4039-b930-95181f41ef5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#content > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[normalize-space()='Checkout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cfa1d95e-b065-4aee-abb0-e9ee2a97af89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your order has been placed!</value>
      <webElementGuid>d160a63b-d36f-47e0-9aa9-de41acb076e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/h1[1]</value>
      <webElementGuid>4316b58e-dc61-4941-ae3b-453a52879f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/h1</value>
      <webElementGuid>8d5898b8-43a1-4dbb-aef8-d58c108af297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h1</value>
      <webElementGuid>649ff67b-7b23-42c2-97fc-75845f205a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Your order has been placed!' or . = 'Your order has been placed!')]</value>
      <webElementGuid>094a6681-8c9f-4760-bf81-b7ea8689efa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
