<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_agree</name>
   <tag></tag>
   <elementGuidId>0036a985-5e5c-4d30-882e-69d43b5217c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='agree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;agree&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32d0cb70-01b4-4d10-90e5-e1225ea95c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c0077597-869a-4156-ab75-0460bf15d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agree</value>
      <webElementGuid>a3a7752a-84a3-4a7a-a3bf-f993a52b0b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>49a7bfda-d142-412b-9112-e7f104bce1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse-payment-method&quot;)/div[@class=&quot;panel-body&quot;]/div[@class=&quot;buttons&quot;]/div[@class=&quot;pull-right&quot;]/input[1]</value>
      <webElementGuid>5ac1dd4a-1c85-4e26-9b77-1a11fe34298c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='agree']</value>
      <webElementGuid>ed69c82a-32b7-4ddd-becc-2a8a6ec20ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-payment-method']/div/div[3]/div/input</value>
      <webElementGuid>fe57ef7e-98f6-4740-93da-96b8357bf6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/input</value>
      <webElementGuid>73e14fdc-c32b-4499-b9bd-c9a95f8821fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'agree']</value>
      <webElementGuid>474be7f6-efd5-4979-9a5d-7188454e8a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
