<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terms  Conditions_button-payment-method</name>
   <tag></tag>
   <elementGuidId>2b58ceeb-e8bc-4843-ba6f-848cc987765f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-payment-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-payment-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8f46848-7cc3-4f8e-a106-aa3f6f5b6452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c06fd7fa-915e-4331-97bb-df1627fd6bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>42946709-38eb-4437-8314-156c2f3c0e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-payment-method</value>
      <webElementGuid>a4dc2aec-1285-48ba-87f6-3baec3717ec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>83b94529-726e-4033-8d4f-a365f636cf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>7d9f732d-1542-44a1-8f91-4c4b9ad0e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-payment-method&quot;)</value>
      <webElementGuid>cb1cd60b-77b3-4eb5-ac86-ab2fdf3afb82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-payment-method']</value>
      <webElementGuid>301f8d81-deee-48b9-a863-a3cf5062f2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-payment-method']/div/div[3]/div/input[2]</value>
      <webElementGuid>adb4ddc8-8880-4bfd-9121-b1137b86597b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>18705927-196c-4884-b6c2-6b8f427b9b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-payment-method']</value>
      <webElementGuid>25fed2d0-dfaa-4701-b794-8bf874a51f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
