<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address 1_address_1</name>
   <tag></tag>
   <elementGuidId>6533aee3-f274-4a9b-b0a5-2540d068c492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-payment-address-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-payment-address-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>502ac760-fa15-4ec3-8285-a640451413be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef8879e6-c7b8-471c-99e8-78e8cf607fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_1</value>
      <webElementGuid>facaaf4d-8b6c-4b07-aec5-31435a9f7cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 1</value>
      <webElementGuid>eb4f1f20-7bf3-4bf9-aeee-d68056b0219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-address-1</value>
      <webElementGuid>e31c30a1-c770-4c92-8c29-707602fe48a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a70d49b3-fe70-4f2d-ab7b-59ca917d01b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-address-1&quot;)</value>
      <webElementGuid>f24ccad9-3f9e-466a-914b-92399082194a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-payment-address-1']</value>
      <webElementGuid>cd43be88-a993-4ed5-b300-6a373b774fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-new']/div[4]/div/input</value>
      <webElementGuid>43a24848-a96a-4ee1-91e5-fa78388eedab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>93907b7e-6db0-4d84-8040-bc377c7c0777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'address_1' and @placeholder = 'Address 1' and @id = 'input-payment-address-1']</value>
      <webElementGuid>6c6a8d65-83e8-4221-8af1-7f3ced638a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
