<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shipping_address</name>
   <tag></tag>
   <elementGuidId>8efcfeba-fbc7-4565-a0f1-82c3d3394d61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='shipping_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;shipping_address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6b34f26-ef0b-447e-aafa-c076de5e92ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ab5e8eb2-3c97-47c6-8e0a-3abac0a41b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>shipping_address</value>
      <webElementGuid>155d8588-f307-4023-bcf1-82047d3d6ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>existing</value>
      <webElementGuid>a27ff010-716a-49fb-9c8b-510c96de6786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>4945be7f-abf8-493f-b39b-ab754555a13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse-shipping-address&quot;)/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;radio&quot;]/label[1]/input[1]</value>
      <webElementGuid>04b26105-14d1-4d02-8dc3-57d0ed3a10a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='shipping_address']</value>
      <webElementGuid>53c93104-1e08-4ed9-b507-c90b57ba2443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-shipping-address']/div/form/div/label/input</value>
      <webElementGuid>2f45f6a4-4abc-4138-acd5-20eb30caf57a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/form/div/label/input</value>
      <webElementGuid>2a10f068-e0c6-4a08-b377-c242985b2470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'shipping_address' and @checked = 'checked']</value>
      <webElementGuid>766989a9-4fc5-4459-8918-21b4add93d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
