<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Comments About Your Order_button-_543ebe</name>
   <tag></tag>
   <elementGuidId>4f2580bb-53c6-4c56-a206-c8727f40b933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-shipping-method</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='button-shipping-method']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a422f36c-dfef-40a4-9597-e2287fec2363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>879c2585-0e67-4a79-9760-da97fba153d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>18ff43a4-b9d5-47aa-86bb-0c6243f27886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-shipping-method</value>
      <webElementGuid>6bdd4804-461d-4c64-b02c-62de8ee6b956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading-text</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>540cc800-fc35-4cb3-9a3b-f32e83b5cd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9114eb7e-a458-4366-9112-c96c677cdbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-shipping-method&quot;)</value>
      <webElementGuid>cad7ec34-d5b7-467b-847a-ca6200420d54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='button-shipping-method']</value>
      <webElementGuid>7ee72f7f-7f93-4aae-9ebf-f6c4e241123c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-shipping-method']/div/div[2]/div/input</value>
      <webElementGuid>8fd9b72e-3cfe-4328-9b50-45982c22bc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>31ddedb7-2418-470f-aa7b-357a7f15df4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'button-shipping-method']</value>
      <webElementGuid>bf2d4d67-5151-436a-a883-1e417b6d30e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
