<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- ArtigasCanelon_9a742f</name>
   <tag></tag>
   <elementGuidId>055a7818-c2b5-45fd-af85-c29a478e6c3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-payment-zone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input-payment-zone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de6b934e-15ab-4578-bc9f-545b61c0f542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>2e329a06-0752-477e-b793-09a21c1c1040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-payment-zone</value>
      <webElementGuid>ce4f648f-314b-416d-ac3a-1dc012a05a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>37e4aff6-7721-4c3a-810a-5037f3d0c2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres</value>
      <webElementGuid>f4b538fe-db04-46d5-a84d-297e8569750e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-payment-zone&quot;)</value>
      <webElementGuid>5bdc07dc-9247-4091-ad95-acddbadda9d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input-payment-zone']</value>
      <webElementGuid>87798642-960e-4062-b2f3-0e6474496808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-new']/div[9]/div/select</value>
      <webElementGuid>afde26f2-20a0-482f-a214-42012f2373e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State'])[1]/following::select[1]</value>
      <webElementGuid>a364513b-0561-4451-a63c-9c2cee8eb8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[2]</value>
      <webElementGuid>c812c309-a9a6-46ff-8588-ceff72fe898c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 3: Payment Method'])[1]/preceding::select[1]</value>
      <webElementGuid>1ec54f9f-194e-4f6e-85d5-d5d7b1c7c7d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 4: Confirm Order'])[1]/preceding::select[1]</value>
      <webElementGuid>a6377bea-3f3b-4fd3-b5b3-dcb08c96109b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/select</value>
      <webElementGuid>94c3843a-c140-49e2-86cd-8f0c378930dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'input-payment-zone' and (text() = ' --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres' or . = ' --- Please Select --- ArtigasCanelonesCerro LargoColoniaDuraznoFloresFloridaLavallejaMaldonadoMontevideoPaysanduRio NegroRiveraRochaSaltoSan JoseSorianoTacuaremboTreinta y Tres')]</value>
      <webElementGuid>eb1697f1-4d6f-4fab-9e18-d97892b8d760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
