<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Success</name>
   <tag></tag>
   <elementGuidId>c6c512b2-5dc7-4788-9138-29eca314602f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-search']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.alert.alert-success.alert-dismissible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f420399-851b-4e7f-ba7c-0e13b376e137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success alert-dismissible</value>
      <webElementGuid>470de27c-4ca3-490a-a431-82d356ca3764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Success: You have added Samsung SyncMaster 941BW to your shopping cart! ×</value>
      <webElementGuid>d3a3c225-681c-4ab6-85e7-0d2eae84078e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-search&quot;)/div[@class=&quot;alert alert-success alert-dismissible&quot;]</value>
      <webElementGuid>3129be8e-99b1-4fbe-9127-6a0fda28cad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-search']/div</value>
      <webElementGuid>dcd26b09-2a4b-4641-9a86-1d5ef2f1e663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>2ce72af8-2a71-48d0-b9a1-6e4c63a4bcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Success: You have added Samsung SyncMaster 941BW to your shopping cart! ×' or . = ' Success: You have added Samsung SyncMaster 941BW to your shopping cart! ×')]</value>
      <webElementGuid>8ef1838f-132f-4f51-b5e6-3eb204b5ac49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
